/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckgRSA;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.math.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Dictionary;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;
import javax.swing.event.ChangeListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/**
 *
 * @author user
 */
public class RSA extends javax.swing.JFrame {

    /**
     * Creates new form RSA
     */
    private final static BigInteger one = new BigInteger("1");
    private final static SecureRandom random = new SecureRandom();
    private BigInteger privateKey;
    private BigInteger publicKey;
    private BigInteger modulus;
    private BufferedImage p;
    private String message;
    private String filename;
    private String mesout;
    private String fileout;
    int k,m;
    //AES a;
    AES8 a;
    spiral4 sp;
    //private BigInteger encrypt;
    //private BigInteger decrypt;
    public RSA() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lock.png")));
        BufferedImage img = null;
        File f=new File("src\\pckgRSA\\defimg.png");
        //System.out.println(f.getAbsolutePath());
        try {
            //img = ImageIO.read(new File(f.getAbsolutePath()));
          // img = ImageIO.read(new File("D:\\Users\\user\\Documents\\NetBeansProjects\\RSA\\src\\pckgRSA\\defimg.png"));
          img = ImageIO.read(new File("images\\defimg.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        jLabel1.setIcon(imageIcon);
        jFrame1.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lock.png")));
       BufferedImage img2 = null;
       File f2=new File("src\\pckgRSA\\ch2.jpg");
        try {
            //img2 = ImageIO.read(new File(f2.getAbsolutePath()));
            //img2 = ImageIO.read(new File("D:\\Users\\user\\Documents\\NetBeansProjects\\STEG04_4\\src\\pckgRSA\\ch2.jpg"));
            img2 = ImageIO.read(new File("images\\ch2.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg2 = img2.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imageIcon2 = new ImageIcon(dimg2);
        jLabel7.setIcon(imageIcon2);
        
        Dictionary dictionary = jSlider1.getLabelTable();
      if (dictionary != null) {
         Enumeration keys = dictionary.keys();
         while (keys.hasMoreElements()) {
            JLabel label = (JLabel) dictionary.get(keys.nextElement());
            label.setForeground(Color.LIGHT_GRAY);
         }
      }
      a=new AES8();
     // a=new AES3();
      sp=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFrame2 = new javax.swing.JFrame();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton18 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jSlider1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jSlider1.setMajorTickSpacing(500);
        jSlider1.setMaximum(4096);
        jSlider1.setMinimum(50);
        jSlider1.setPaintLabels(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("KEY SIZE :");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("PUBLIC KEY :");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("PRIVATE KEY :");

        jButton12.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton12.setText("GENERATE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton19.setText("DONE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel5))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton16.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton16.setText("SAVE");

        jButton17.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton17.setText("IMPORT");

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel10.setText(" CHOOSE FILE :");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame2Layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(77, 77, 77)))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame2Layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField4)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mYsTEGOaPP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName(""); // NOI18N
        jTextArea1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextArea1InputMethodTextChanged(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton1.setText("ENCRYPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton3.setText("RETRIEVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton2.setText("DECRYPT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton4.setText("HIDE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton5.setText("GENERATE KEY");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton7.setText("CHOOSE KEY");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton8.setText("CHOOSE IMAGE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton9.setText("SEND / RECEIVE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton10.setText("ANALYZE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ENCRYPTION ALGORITHM :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("RSA");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("AES");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("STEGANOGRAPHY ALGORITHM :");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("LSB");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton4.setText("Modified LSB");

        jButton18.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton18.setText("SAVE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton13.setText("OPEN");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton11.setText("?");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(927, 927, 927)
                .addComponent(jButton11))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(522, 522, 522)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jRadioButton4))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jRadioButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jRadioButton3))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jRadioButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jRadioButton4))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jRadioButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jRadioButton3))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jRadioButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public BigInteger encrypt(BigInteger message) {
      return message.modPow(publicKey, modulus);
    }

    public BigInteger decrypt(BigInteger encrypted) {
      return encrypted.modPow(privateKey, modulus);
    }
    public int[] bin(int a)
	{
		int n=a;
		int count=0;
		int b[];
		int r;
		
		//System.out.println(len);
		b=new int[8];
		while(n>0)
		{
			r=n%2;
			b[count++]=r;
			n=n/2;
		}
		while(count<8)
			b[count++]=0;
		return b;
	}
	public int dec(int []a)
	{
		int sum=0;
		for(int i=0;i<a.length;i++)
		{
			sum=sum+(int)(Math.pow(2,i)*a[i]);
		}
		return sum;
	}
		
	public int nextbit()
	{
		
		try 
		{
			byte arr[]= message.getBytes( "UTF-8" );
			//System.out.println("k="+k +" m="+m);
			while(k<arr.length)
			{
				int arr2[]=bin(arr[k]);
				while(m<arr2.length)
				{
					return arr2[m++];		
				}
				
				k++;
				m=0;

			}
		}
		catch( Exception e) 
		{
			System.out.println("Unsupported character set");
		}
		return -1;
	}
    public void convert() throws IOException
	{
		int t=0,q=0,nb=-1,cnt=1,rgb;
		//System.out.println("Hidding Message...");
		while(cnt<=3)
		{
			for (int i = 0; i < p.getWidth(); i++) 
			{
				for (int j = 0; j < p.getHeight(); j++) 
				{
					Color c = new Color(p.getRGB(i, j));
					int r=c.getRed();
					int g=c.getGreen();
					int b=c.getBlue();
                                        //jTextArea2.setText(jTextArea2.getText()+"\r\n"+c);
					rgb=r;
					nb=nextbit();
                                       // jTextArea2.setText(jTextArea2.getText()+"\r\n"+nb);
					switch(cnt)
					{
						case 1:
							rgb=r;
						case 2:
							rgb=g;
						case 3:
							rgb=b;
					}
					if(nb==-1) break;
					if(nb!=-1)
					{
						if((rgb%2==0)&&(nb==1))
							rgb++;
						else if((rgb%2==1)&&(nb==0))
							rgb--;
						switch(cnt)
						{
							case 1:
								c=new Color(rgb,g,b);
							case 2:
								c=new Color(r,rgb,b);
							case 3:
								c=new Color(r,g,rgb);
						}
						p.setRGB(i, j, c.getRGB());
						q=j+1;
					}
				}
				if(nb==-1) break;
				t=i+1;
			}
		
			if(nb==-1)
			{ 
				int count=0,ev;
                                while(true){
				for (; t< p.getWidth()&&count<8; t++) 
				{
					for (; q < p.getHeight()&&count<8; q++) 
					{
						Color c = new Color(p.getRGB(t, q));
						int r=c.getRed();
						int g=c.getGreen();
						int b=c.getBlue();
                                               // jTextArea2.setText(jTextArea2.getText()+"\r\n"+c);
						rgb=r;
						switch(cnt)
						{
							case 1:
								rgb=r;
							case 2:
								rgb=g;
							case 3:
								rgb=b;
						}
						if(rgb%2==1)
							rgb--;
						switch(cnt)
						{
							case 1:
								c=new Color(rgb,g,b);
							case 2:
								c=new Color(r,rgb,b);
							case 3:
								c=new Color(r,g,rgb);
						}
						p.setRGB(t, q, c.getRGB());
						count++;
						//ev=r%2;
						//System.out.println(ev);
					}
				}
                                if(count==8)
                                    return;
                                else{
                                    cnt++;
                                    t=0;
                                    q=0;
                                }
                                }
			}
			cnt++;
		}
		//System.out.println("Message is successfully hidden.");
		//String suffix = fileout.substring(fileout.lastIndexOf('.') + 1);
		//File outputfile = new File(fileout);
		//ImageIO.write(p, suffix, outputfile);
    }
	public void unconvert()
	{
		int count=0,ch,d,cnt=1,rgb;
		char chr;
		int a[]=new int[8];
		//System.out.println("Recovering Message...");
		while(cnt<=3)
		{
			for (int i = 0; i < p.getWidth(); i++) 
			{
				for (int j = 0; j < p.getHeight(); j++) 
				{
					Color c = new Color(p.getRGB(i, j));
					int r=c.getRed();
					int g=c.getGreen();
					int b=c.getBlue();
                                       // jTextArea2.setText(jTextArea2.getText()+"\r\n"+c);
					rgb=r;
					switch(cnt)
					{
						case 1:
							rgb=r;
						case 2:
							rgb=g;
						case 3:
							rgb=b;
					}
					if(rgb%2==0)
						ch=0;
					else	
						ch=1;
					a[count++]=ch;
					if(count==8)
					{
						d=dec(a);
						chr=(char)d;
                                               // System.out.println(chr);
						if(chr=='\0')
							return;
						mesout=mesout.concat(Character.toString(chr));
						//jTextArea1.setText(mesout);
						count=0;
					}
				}
			}
			cnt++;
		//System.out.println(mesout);
		}
	}  
	public void pr()
	{
		jTextArea1.setText(mesout);
	}
        public void sound(){
        InputStream music;
        try{
        music=new FileInputStream(new File("images\\buttonpush.wav"));
        AudioStream audios=new AudioStream(music);
        AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
        } 
        }
        public void sound2(){
        InputStream music;
        try{
        music=new FileInputStream(new File("images\\beep.wav"));
        AudioStream audios=new AudioStream(music);
        AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
        } 
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sound();
        String sencrypt="";
        String s=jTextArea1.getText();
        System.out.println(s.length());
        System.out.println((""+modulus).length());
        if(jTextArea1.getText().length()==0)
       {
           sound2();
           jTextArea2.setText("Hey, there is no message!!");
       }
        if(jRadioButton1.isSelected()){
          byte[] bytes = s.getBytes();
        BigInteger message = new BigInteger(bytes);
        if(message.bitLength()>4096){
            sound2();
            jTextArea2.setText("Sorry too long message.\r\n But you can divide it ino smaller parts and then encrypt or use symmetric key encryption. :)");
            return;
        }
        else if(message.bitLength()>=modulus.bitLength())
        {
            sound2();
            jTextArea2.setText("Either no key is used or use a larger key. :)");
            return;
        }
        BigInteger encrypt = encrypt(message);
        sencrypt=""+encrypt;
        
         
        }
        else{
        sencrypt=a.encrypt(s);
        }
        jTextArea1.setText(sencrypt);
        jTextArea2.setText("Successfully Encrypted! :)");
      //  jTextArea1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       /* jFrame1.setVisible(true);
        jFrame1.pack();
        jFrame1.setLocationRelativeTo(null);
        sound();*/
        sound();
        if(jTextArea1.getText().length()==0)
       {
           sound2();
           jTextArea2.setText("Hey, there is no message!!");
       }
        String sdecrypt="";
        String str=jTextArea1.getText();
        if(jRadioButton1.isSelected()){
        BigInteger encrypt=new BigInteger(str);
        BigInteger decrypt = decrypt(encrypt);
        sdecrypt=new String(decrypt.toByteArray());
        }
        else{
            sdecrypt=a.decrypt(str);
        }
        jTextArea1.setText(sdecrypt);
        jTextArea2.setText("Successfully decrepted! :)");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jRadioButton1.isSelected())
        {
            sound();
            jFrame1.setVisible(true);
            BufferedImage img3 = null;
            File f3=new File("src\\pckgRSA\\choose10.jpg");
            try {
               // img3 = ImageIO.read(new File(f3.getAbsolutePath()));
               //img3 = ImageIO.read(new File("D:\\Users\\user\\Documents\\NetBeansProjects\\STEG04_4\\src\\pckgRSA\\choose10.jpg"));
                img3 = ImageIO.read(new File("images\\choose10.jpg"));
            } catch (IOException e) {
                e.printStackTrace();
            }
            Image dimg3 = img3.getScaledInstance(jLabel11.getWidth(), jLabel11.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon imageIcon3 = new ImageIcon(dimg3);
            jLabel11.setIcon(imageIcon3);
            jFrame1.pack();
            jFrame1.setLocationRelativeTo(null);
            
        }
        else
        {
            sound();
            String key=a.gen();
            JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Key");
        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            sound();
            File f = fileChooser.getSelectedFile();
            String filename=f.getAbsolutePath();
            try{
            BufferedWriter bw = new BufferedWriter(new FileWriter(filename));
            bw.write(key);
            bw.close();
            
            }catch(IOException e)
            {   
            }
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(jRadioButton1.isSelected())
        {
        sound();
        JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Open Public Key");
        int userselection=chooser.showOpenDialog(null);
        if (userselection == JFileChooser.APPROVE_OPTION) {
        sound();
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField1.setText(filename);
        }
       JFileChooser chooser2=new JFileChooser();
        chooser2.setDialogTitle("Open Private Key");
        int userselection2=chooser2.showOpenDialog(null);
        if (userselection2 == JFileChooser.APPROVE_OPTION) {
        sound();
        File f2=chooser2.getSelectedFile();
        String filename2=f2.getAbsolutePath();
        jTextField2.setText(filename2);
        }
        /*JFileChooser chooser3=new JFileChooser();
        chooser3.setDialogTitle("Open Modulus Key");
        int userselection3=chooser3.showOpenDialog(null);
        if (userselection3 == JFileChooser.APPROVE_OPTION) {
        sound();
        File f3=chooser3.getSelectedFile();
        String filename3=f3.getAbsolutePath();
        jTextField3.setText(filename3);
        }*/
        String fname=jTextField1.getText();
        String s="";
        String ss2="";
        //jTextArea2.setText(fname);
        try{
        Scanner sc = new Scanner(new File(fname));
        sc.useDelimiter(";");
        /*while (sc.hasNext()) {
           s=s + sc.next();
          if (s.trim().isEmpty()) {
            continue;
          }
         
        }*/
       // br.close();
       s=sc.next();
       s=s.trim();
       System.out.println(s);
       ss2=sc.next();
       ss2=ss2.trim();
       System.out.println(ss2);
        }catch(IOException e)
        {   
        }
        //jTextArea2.setText(s);
        publicKey=new BigInteger(s);
        modulus=new BigInteger(ss2);
        String fname2=jTextField2.getText();
        String s2="";
      //  jTextArea2.setText(fname2);
        try{
        Scanner sc = new Scanner(new File(fname2));
        sc.useDelimiter("");
        while (sc.hasNext()) {
           s2=s2 + sc.next();
          if (s2.trim().isEmpty()) {
            continue;
          }
         
        }
        System.out.println(s2);
       // br.close();
        }catch(IOException e)
        {   
        }
        //jTextArea2.setText(s2);
        privateKey=new BigInteger(s2);
       /* String fname3=jTextField3.getText();
        String s3="";
       // jTextArea2.setText(fname3);
        try{
        Scanner sc = new Scanner(new File(fname3));
        sc.useDelimiter("");
        while (sc.hasNext()) {
           s3=s3 + sc.next();
          if (s3.trim().isEmpty()) {
            continue;
          }
         
        }
       // br.close();
        }catch(IOException e)
        {   
        }
       // jTextArea2.setText(s3);
        modulus=new BigInteger(s3);*/
        }
        else
        {
            sound();
            JFileChooser chooser=new JFileChooser();
            chooser.setDialogTitle("Open Key");
            int userselection=chooser.showOpenDialog(null);
            if (userselection == JFileChooser.APPROVE_OPTION) {
            sound();
            File f=chooser.getSelectedFile();
            String filename=f.getAbsolutePath();
           // jTextField1.setText(filename);
            String s="";
            String s2="";
            String ch="";
            try{
                Scanner sc = new Scanner(new File(filename));
                sc.useDelimiter(";");
                /*while (sc.hasNext()) {
                   ch=sc.next();
                   s=s + ch;
                   System.out.println(ch);
                  if (s.trim().isEmpty()) {
                    continue;
                    
                  }
                
                }*/
                s=sc.next();
                s.trim();
                s2=sc.next();
                s2.trim();
       // br.close();
       
                }catch(IOException e)
                {   
                }
           //a.modkey(s);
        //   System.out.println(s);
        //   System.out.println(s2);
         a.modkey2(s,s2);
        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        sound();
        JFileChooser chooser=new JFileChooser();
        int userselection=chooser.showOpenDialog(null);
        if (userselection == JFileChooser.APPROVE_OPTION) {
        sound();
        File f=chooser.getSelectedFile();
        // File f=new File("tiger.bmp");
       try{
            Image image = ImageIO.read(f);
            Image dimg = image.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
            
            ImageIcon icon = new ImageIcon(dimg);
            // JLabel toBeSet = new JLabel(); 
            // considering that you have a JLabel having name as what I've used here
            jLabel1.setIcon(icon);
            }
        catch(IOException ioe){
            System.out.println("Exception occured ");
        }
        filename=f.getAbsolutePath();
        
        try{
        p = ImageIO.read(new File(filename));
        }catch(IOException e){
        }
        }
	k=0;
	m=0;
	mesout="";
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       sound();
       if(jTextArea1.getText().length()==0)
       {
           sound2();
           jTextArea2.setText("Hey, there is no message!!");
       }
        message = jTextArea1.getText();
        try{
        sp=new spiral4(p,message);
        }
        catch(IOException e){ }
        BufferedImage p1=null;
        try { 
            if(jRadioButton3.isSelected()){
            convert();
            }
            else{
            p1=sp.convert2();
            }
        } catch (IOException ex) {
           System.out.println("Error occured");
        }
       JFileChooser fileChooser = new JFileChooser();
       fileChooser.setDialogTitle("Save Image Key");
       int userSelection = fileChooser.showSaveDialog(null);
       if (userSelection == JFileChooser.APPROVE_OPTION) {
           sound();
            File f = fileChooser.getSelectedFile();
            String filo=f.getAbsolutePath();
       fileout=filo;
       String suffix = fileout.substring(fileout.lastIndexOf('.') + 1);
       File outputfile = new File(fileout);
       try {
            if(jRadioButton3.isSelected()){
            ImageIO.write(p, suffix, outputfile);
            }
            else
                ImageIO.write(p1, suffix, outputfile);
            Image image = ImageIO.read(f);
            Image dimg = image.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
            
            ImageIcon icon = new ImageIcon(dimg);
            //ImageIcon icon = new ImageIcon(image);
            jLabel1.setIcon(icon);
            jTextArea2.setText("The message is successfully hidden! :)");
        } catch (IOException e) {
            
        }
       
       }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        sound(); 
       /* if(jTextArea1.getText().length()==0)
       {
           sound2();
           jTextArea2.setText("Hey, there is no message!!");
       }*/
        if(jRadioButton3.isSelected()){
        unconvert();
            pr();
        }
        else{
            try { 
                sp=new spiral4(p,"");
            } catch (IOException ex) {
               
            }
            mesout=sp.unconvert2();
            pr();
            
        }
            
            jTextArea2.setText("The message is successfully retrieved. :)");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        sound();
        try {
                 //Desktop.getDesktop().browse(new URI("https://mail.google.com/mail/u/0/?tab=wm#inbox?compose=new"));
                Desktop.getDesktop().mail();
                
             }
         catch (IOException e) {
            System.out.println(e);
           
        
        }
       /* catch (URISyntaxException ex) {
                
             }*/
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        sound();
        String str=jTextArea1.getText();
        jTextArea2.setText("There are " + (jTextArea1.getText()).length() + " characters in this message.");
        int blen=new BigInteger(jTextArea1.getText().getBytes()).bitLength();
        jTextArea2.setText(jTextArea2.getText()+"\r\nThe size of message is " + blen+ " bits.");
        if(jRadioButton1.isSelected()){
        jTextArea2.setText(jTextArea2.getText()+"\r\nGenerate or choose a key of size " + blen+ " bits");
        }
        if(p!=null){
        int clen=p.getWidth()*p.getHeight()*3/8;
       
        jTextArea2.setText(jTextArea2.getText()+"\r\nYou can hide approximately "+clen+" characters in this image. :)");
        
        if (str.length()>=clen)
        {
            jTextArea2.setText(jTextArea2.getText()+"\r\nMessage is too long for image.\r\n. You might either consider using a greater resolution image or using a shorter key. :)");
        }
        else
            jTextArea2.setText(jTextArea2.getText()+"\r\nYou are good to go. :)");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        sound();
        jTextArea1.setText(""); 

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextArea1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextArea1InputMethodTextChanged
        //  jTextArea2.setText(""+(jTextArea1.getText()).length()+" words");
    }//GEN-LAST:event_jTextArea1InputMethodTextChanged

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
       jTextArea2.setText(""+((jTextArea1.getText()).length()+1 )+" Characters");
       if((jTextArea1.getText()).length()==512)
        sound2();
       if((jTextArea1.getText()).length()>=512){
           
           String s=":-( Maximum Limit Reached...if you are trying to encrypt the message else you can carry on... ";
           jTextArea2.setText(s+"\r\n"+(jTextArea1.getText()).length()+" Characters"+"\r\n");
    }//GEN-LAST:event_jTextArea1KeyTyped
    }
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        sound();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Message");
        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            sound();
            File f = fileChooser.getSelectedFile();
            String filename=f.getAbsolutePath();
            try{
            BufferedWriter bw = new BufferedWriter(new FileWriter(filename));
            bw.write(jTextArea1.getText());
            bw.close();
            
            }catch(IOException e)
            {   
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        sound();
        JFileChooser chooser=new JFileChooser();
        int userselection=chooser.showOpenDialog(null);
        if (userselection == JFileChooser.APPROVE_OPTION) {
        sound();
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        String str="";
        int scl;
        try{
            BufferedReader br = new BufferedReader(new FileReader(filename));
            while((scl=br.read())!=-1){
            str=str + (char)scl;
            }
            jTextArea1.setText(str);
            br.close();
            
            }catch(IOException e)
            {   
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        sound();
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        sound();
        int N=jSlider1.getValue();
        System.out.println(N);
        BigInteger p,q;
       // do{
        p = BigInteger.probablePrime(N/2, random);
        q = BigInteger.probablePrime(N/2, random);
        
        //jTextArea2.setText(""+p+" "+q);
        BigInteger phi = (p.subtract(one)).multiply(q.subtract(one));
        modulus    = p.multiply(q);
        publicKey  = new BigInteger("65537");
        privateKey = publicKey.modInverse(phi);
       // }while(modulus.bitLength()<N);
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Public Key");
        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            sound();
            File f = fileChooser.getSelectedFile();
            String filename=f.getAbsolutePath();
            try{
                BufferedWriter bw = new BufferedWriter(new FileWriter(filename));
                String pubkey=""+publicKey+";"+modulus;
                bw.write(pubkey);
                bw.close();

            }catch(IOException e)
            {
            }

            jTextField1.setText(filename);
        }
        JFileChooser fileChooser2 = new JFileChooser();
        fileChooser2.setDialogTitle("Save Private Key");
        int userSelection2 = fileChooser2.showSaveDialog(null);
        if (userSelection2 == JFileChooser.APPROVE_OPTION) {
            sound();
            File f2 = fileChooser2.getSelectedFile();
            String filename2=f2.getAbsolutePath();
            try{
                BufferedWriter bw = new BufferedWriter(new FileWriter(filename2));
                String prikey=""+privateKey;
                bw.write(prikey);
                bw.close();
            }catch(IOException e)
            {
            }

            jTextField2.setText(filename2);
        }
        /*  JFileChooser fileChooser3 = new JFileChooser();
        fileChooser3.setDialogTitle("Save Modulus Key");
        int userSelection3 = fileChooser3.showSaveDialog(null);
        if (userSelection3 == JFileChooser.APPROVE_OPTION) {
            sound();
            File f3 = fileChooser3.getSelectedFile();
            String filename3=f3.getAbsolutePath();
            try{
                BufferedWriter bw = new BufferedWriter(new FileWriter(filename3));
                String mod=""+modulus;
                bw.write(mod);
                bw.close();
            }catch(IOException e)
            {
            }
            jTextField3.setText(filename3);
        }*/
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        jLabel6.setText(""+jSlider1.getValue()+" bits");
    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         sound();
         //File f = new File("src\\pckgRSA\\webpage\\index2.html"); 
         File f = new File("webpage\\index2.html"); 
         //System.out.println("f.getAbsolutePath() = " + f.getAbsolutePath());
         //System.out.println(f.toURI().toString());
         
         try{
		Desktop.getDesktop().browse(new URI(f.toURI().toString()));
            }catch(Exception e)
            { System.out.println(e);}
        
       
    }//GEN-LAST:event_jButton11ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
